version: '3.8'

services:
  xss-tester:
    build: xss_tester
    expose:
      - "8080:8080"
    external_links:
      - app:app
    init: true
  
  app:
    build: app
    ports:
      - "8004:80"
    external_links:
        - xss-tester:xss-tester
    volumes:
      - ./app:/app
      # - ./data:/app/data
    init: true