FROM python:3.10

RUN echo "deb http://deb.debian.org/debian/ unstable main contrib non-free" >> /etc/apt/sources.list.d/debian.list
RUN apt update
RUN apt install -y gcc
RUN apt install -y firefox

WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .
ADD bin /usr/bin

VOLUME data/ data/

CMD [ "python3", "app.py" ]